---
title: "boostrap_examples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(datasets.load)
library(dplyr)
library(ggplot2)
library(boot)
library(car)
library(rTPC)
library(nls.multstart)
library(broom)
library(tidyverse)
library(patchwork)
library(minpack.lm)
library(nlstools)
library(extrafont)
loadfonts(device = "win")

```

# Models for a singe curve

## Read in data
```{r,include=F}
gb_t<-growth.alive%>%filter(pop=="Great Bay")
gb_t<-gb_t%>%filter(bin==3)
gb_t<-na.omit(gb_t)
gb_t<-data.frame("temp"=gb_t$temp,"cal.length"=gb_t$cal.length,"bin"=gb_t$bin,"pop"=gb_t$pop)

```

# Create model and plot

```{r,warning=F,echo=F}

# fit five chosen model formulations in rTPC
d_fits <- nest(gb_t, data = c(temp, cal.length)) %>%
  mutate(rezende = map(data, ~nls_multstart(cal.length~rezende_2019(temp = temp, q10,a,b,c),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'rezende_2019') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'rezende_2019') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'rezende_2019'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'rezende_2019'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         boatman = map(data, ~nls_multstart(cal.length~boatman_2017(temp = temp, rmax, tmin, tmax, a, b),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'boatman_2017') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'boatman_2017') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'boatman_2017'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'boatman_2017'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         briere2 = map(data, ~nls_multstart(cal.length~briere2_1999(temp = temp, tmin, tmax, a, b),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'briere2_1999') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'briere2_1999') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'briere2_1999'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'briere2_1999'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         
         lactin = map(data, ~nls_multstart(cal.length~lactin2_1995(temp = temp, a, b, tmax, delta_t),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'lactin2_1995') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'lactin2_1995') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'lactin2_1995'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'lactin2_1995'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
          modifiedgaussian = map(data, ~nls_multstart(cal.length~modifiedgaussian_2006(temp = temp, rmax, topt, a, b),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'modifiedgaussian_2006') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'modifiedgaussian_2006') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'modifiedgaussian_2006'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'modifiedgaussian_2006'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         spain = map(data, ~nls_multstart(cal.length~spain_1982(temp = temp, a, b, c, r0),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'spain_1982') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'spain_1982') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'spain_1982'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'spain_1982'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         beta = map(data, ~nls_multstart(cal.length~beta_2012(temp = temp, a, b, c, d, e),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'beta_2012') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'beta_2012') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'beta_2012'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'beta_2012'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         thomas = map(data, ~nls_multstart(cal.length~thomas_2017(temp = temp, a, b, c, d, e),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'thomas_2017') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'thomas_2017') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'thomas_2017'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'thomas_2017'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         delong = map(data, ~nls_multstart(cal.length~thomas_2017(temp = temp, c, eb, ef, tm, ehc),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'delong_2017') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'delong_2017') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'delong_2017'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'delong_2017'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         flinn = map(data, ~nls_multstart(cal.length~flinn_1991(temp = temp, a,b,c),
                                                     data = .x,
                                                     iter = c(3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'flinn_1991') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'flinn_1991') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'flinn_1991'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'flinn_1991'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),


         gaussian_old = map(data, ~nls_multstart(cal.length~gaussian_1987(temp = temp, rmax, topt, a),
                                                     data = .x,
                                                     iter = c(3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'gaussian_1987') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'gaussian_1987') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'gaussian_1987'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'gaussian_1987'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         
         oneill = map(data, ~nls_multstart(cal.length~oneill_1972(temp = temp, rmax, ctmax, topt, q10),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'oneill_1972') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'oneill_1972') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'oneill_1972'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'oneill_1972'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         
          ratkowsky = map(data, ~nls_multstart(cal.length~ratkowsky_1983(temp = temp, tmin, tmax, a, b),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'ratkowsky_1983') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'ratkowsky_1983') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'ratkowsky_1983'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'ratkowsky_1983'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         
         weibull = map(data, ~nls_multstart(cal.length~weibull_1995(temp = temp,a, topt, b, c),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'weibull_1995') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'weibull_1995') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'weibull_1995'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'weibull_1995'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)))
         
         
         


       
# stack models
d_stack <- dplyr::select(d_fits, -data) %>%
  pivot_longer(., names_to = 'model_name', values_to = 'fit', rezende:weibull)

# get predictions using augment
newdata <- tibble(temp = seq(min(d$temp), max(d$temp), length.out = 100))
d_preds <- d_stack %>%
  mutate(., preds = map(fit, augment, newdata = newdata)) %>%
  dplyr::select(-fit) %>%
  unnest(preds)

# take a random point from each model for labelling
d_labs <- filter(d_preds, temp < 30) %>%
  group_by(., model_name) %>%
  sample_n(., 1) %>%
  ungroup()

# plot
ggplot(d_preds, aes(temp, .fitted)) +
  geom_line(aes(col = model_name)) +
  geom_label_repel(aes(temp, .fitted, label = model_name, col = model_name), fill = 'white', nudge_y = 0.8, segment.size = 0.2, segment.colour = 'grey50', d_labs) +
  geom_point(aes(temp, cal.length), gb_t) +
  theme_bw(base_size = 12) +
  theme(legend.position = 'none') 
```

```{r}
d_ic <- d_stack %>%
  mutate(., info = map(fit, glance),
         AICc =  map_dbl(fit, MuMIn::AICc)) %>%
  dplyr::select(-fit) %>%
  unnest(info) %>%
  dplyr::select(model_name, sigma, AIC, AICc, BIC, df.residual)

d_ic
#> # A tibble: 6 x 6
#>   model_name       sigma    AIC  AICc   BIC df.residual
#>   <chr>            <dbl>  <dbl> <dbl> <dbl>       <int>
#> 1 boatman          0.292 10.0    26.8 12.9            7
#> 2 gaussian         0.327 11.8    17.5 13.7            9
#> 3 oneill           0.266  7.38   17.4  9.81           8
#> 4 quadratic        0.408 17.1    22.8 19.0            9
#> 5 rezende          0.362 14.8    24.8 17.2            8
#> 6 sharpeschoolhigh 0.198  0.350  10.3  2.77           8
```