---
title: "boostrap_examples"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(datasets.load)
library(dplyr)
library(ggplot2)
library(boot)
library(car)
library(rTPC)
library(nls.multstart)
library(broom)
library(tidyverse)
library(patchwork)
library(minpack.lm)
library(nlstools)
library(extrafont)
#loadfonts(device = "win")

```

# Models for a singe curve

## Read in data
```{r,include=F}
gb_t<-growth.alive%>%filter(pop=="Humboldt")
gb_t<-gb_t%>%filter(bin==1)
gb_t<-na.omit(gb_t)
gb_t<-data.frame("temp"=gb_t$temp,"cal.length"=gb_t$cal.length,"bin"=gb_t$bin,"pop"=gb_t$pop)

```

# Create model and plot

```{r,warning=F,echo=F}

# fit five chosen model formulations in rTPC
d_fits <- nest(gb_t, data = c(temp, cal.length)) %>%
  mutate(rezende = map(data, ~nls_multstart(cal.length~rezende_2019(temp = temp, q10,a,b,c),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'rezende_2019') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'rezende_2019') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'rezende_2019'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'rezende_2019'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         boatman = map(data, ~nls_multstart(cal.length~boatman_2017(temp = temp, rmax, tmin, tmax, a, b),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'boatman_2017') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'boatman_2017') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'boatman_2017'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'boatman_2017'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         briere2 = map(data, ~nls_multstart(cal.length~briere2_1999(temp = temp, tmin, tmax, a, b),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'briere2_1999') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'briere2_1999') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'briere2_1999'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'briere2_1999'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         
         
         beta = map(data, ~nls_multstart(cal.length~beta_2012(temp = temp, a, b, c, d, e),
                                                     data = .x,
                                                     iter = c(3,3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'beta_2012') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'beta_2012') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'beta_2012'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'beta_2012'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)),
         
         
         weibull = map(data, ~nls_multstart(cal.length~weibull_1995(temp = temp,a, topt, b, c),
                                                     data = .x,
                                                     iter = c(3,3,3,3),
                                                     start_lower = get_start_vals(.x$temp, .x$cal.length, model_name = 'weibull_1995') - 1,
                                                     start_upper = get_start_vals(.x$temp, .x$cal.length, model_name = 'weibull_1995') + 1,
                                                     lower = get_lower_lims(.x$temp, .x$cal.length, model_name = 'weibull_1995'),
                                                     upper = get_upper_lims(.x$temp, .x$cal.length, model_name = 'weibull_1995'),
                                                     supp_errors = 'Y',
                                                     convergence_count = FALSE)))
         
         
         


       
# stack models
d_stack <- dplyr::select(d_fits, -data) %>%
  pivot_longer(., names_to = 'model_name', values_to = 'fit', rezende:weibull)

# get predictions using augment
newdata <- tibble(temp = seq(min(d$temp), max(d$temp), length.out = 100))
d_preds <- d_stack %>%
  mutate(., preds = map(fit, augment, newdata = newdata)) %>%
  dplyr::select(-fit) %>%
  unnest(preds)

# take a random point from each model for labelling
d_labs <- filter(d_preds, temp < 30) %>%
  group_by(., model_name) %>%
  sample_n(., 1) %>%
  ungroup()

# plot
ggplot(d_preds, aes(temp, .fitted)) +
  geom_line(aes(col = model_name)) +
  geom_label_repel(aes(temp, .fitted, label = model_name, col = model_name), fill = 'white', nudge_y = 0.8, segment.size = 0.2, segment.colour = 'grey50', d_labs) +
  geom_point(aes(temp, cal.length), gb_t) +
  theme_bw(base_size = 12) +
  theme(legend.position = 'none') 
```

```{r}
d_ic <- d_stack %>%
  mutate(., info = map(fit, glance),
         AICc =  map_dbl(fit, MuMIn::AICc)) %>%
  dplyr::select(-fit) %>%
  unnest(info) %>%
  dplyr::select(model_name, sigma, AIC, AICc, BIC, df.residual)

d_ic

```